'use client'

import React, { useState, useMemo } from 'react'
import { Search, Receipt, Printer, Eye, Calendar, User } from 'lucide-react'
import type { CompletedInvoice } from './types'

interface InvoiceHistoryProps {
  invoices: CompletedInvoice[]
  isLoading: boolean
  onViewInvoice: (inv: CompletedInvoice) => void
}

export const InvoiceHistory: React.FC<InvoiceHistoryProps> = ({
  invoices,
  isLoading,
  onViewInvoice,
}) => {
  const [search, setSearch] = useState('')

  const filteredInvoices = useMemo(() => {
    return invoices.filter((inv) => {
      const matchNumber = inv.invoice_number.toLowerCase().includes(search.toLowerCase())
      const matchName = inv.customer_name.toLowerCase().includes(search.toLowerCase())
      const matchPhone = (inv.customer_phone || '').includes(search)
      return matchNumber || matchName || matchPhone
    })
  }, [invoices, search])

  return (
    <div className="bg-[#0C0F17] border border-white/10 rounded-lg overflow-hidden shadow-sm flex flex-col h-full">
      {/* Header & Search */}
      <div className="p-4 border-b border-white/10 bg-[#0A0D14] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-white">Sales & Invoice History</h3>
          <p className="text-[11px] text-zinc-400">All retail invoices generated by this register</p>
        </div>

        <div className="relative w-full sm:w-72">
          <Search className="absolute left-3 top-2.5 w-3.5 h-3.5 text-zinc-400" />
          <input
            type="text"
            placeholder="Search by invoice # or client..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 bg-zinc-900 border border-white/10 rounded text-xs text-white placeholder-zinc-400 focus:outline-hidden"
          />
        </div>
      </div>

      {/* Invoices List Table */}
      <div className="flex-1 overflow-y-auto">
        {isLoading ? (
          <div className="p-4 space-y-3">
            {[1, 2, 3, 4].map((i) => (
              <div
                key={i}
                className="h-14 rounded bg-zinc-900/60 border border-white/5 animate-pulse"
              />
            ))}
          </div>
        ) : filteredInvoices.length === 0 ? (
          <div className="h-64 flex flex-col items-center justify-center text-center p-6">
            <Receipt className="w-8 h-8 text-zinc-400 mb-2" />
            <h4 className="text-xs font-semibold text-zinc-200">No invoices recorded yet</h4>
            <p className="text-[11px] text-zinc-400 max-w-xs mt-1">
              {search
                ? 'No invoices match your search query.'
                : 'Invoices created at checkout will appear here for reprint and record keeping.'}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-white/10 text-[10px] font-mono uppercase tracking-wider text-zinc-400 bg-zinc-950/40">
                  <th className="py-2.5 px-4">Invoice #</th>
                  <th className="py-2.5 px-4">Date & Time</th>
                  <th className="py-2.5 px-4">Client</th>
                  <th className="py-2.5 px-4">Payment</th>
                  <th className="py-2.5 px-4 text-right">Amount</th>
                  <th className="py-2.5 px-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 font-sans">
                {filteredInvoices.map((inv) => (
                  <tr key={inv.id} className="hover:bg-zinc-900/50 transition-colors">
                    <td className="py-3 px-4 font-mono font-bold text-white">
                      {inv.invoice_number}
                    </td>
                    <td className="py-3 px-4 text-zinc-400 font-mono text-[11px]">
                      {new Date(inv.created_at).toLocaleDateString('en-IN', {
                        day: '2-digit',
                        month: 'short',
                        year: 'numeric',
                      })}{' '}
                      <span className="text-zinc-600">
                        {new Date(inv.created_at).toLocaleTimeString('en-IN', {
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <p className="font-semibold text-zinc-200">{inv.customer_name}</p>
                      {inv.customer_phone && (
                        <p className="text-[10px] font-mono text-zinc-400">
                          {inv.customer_phone}
                        </p>
                      )}
                    </td>
                    <td className="py-3 px-4">
                      <span className="inline-block px-2 py-0.5 rounded text-[10px] uppercase font-mono bg-zinc-800 text-zinc-300 border border-white/5">
                        {inv.payment_method}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-right font-mono font-bold text-white">
                      ₹{Number(inv.total_amount).toLocaleString('en-IN')}
                    </td>
                    <td className="py-3 px-4 text-right">
                      <button
                        type="button"
                        onClick={() => onViewInvoice(inv)}
                        className="inline-flex items-center space-x-1 px-2.5 py-1 rounded bg-zinc-800 hover:bg-zinc-700 text-xs text-white border border-white/10 transition-colors"
                      >
                        <Printer className="w-3 h-3" />
                        <span>Print</span>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
